Elixir integration
erlanglab/erlangpl pull request #25
Opened 2017-04-01 21:45 UTC by arkgil

After a bit of discussion (#22), I've made it possible to start Elixir on erlangpl node. There are two ways to achieve that:
1. Provide `--with-elixir <elixir_root>` option to `erlangpl` script - this results in prepending code path with given path and starting Elixir application
2. Provide `--with-elixir <elixir_root>` option to `bootstrap` script - this results in **embedding** Elixir directly into `erlangpl` escript. At runtime we simply start Elixir application.

In this setup it is possible to experiment with different Elixir versions - Elixir "passed" to `erlangpl` will override the one embedded in escript (due to code path being prepended - we don't touch anything else).

It seems to be working fine, although to be 100% sure I probably should implement simple Elixir plugin.

Note: path passed both to `bootstrap` or `erlangpl` needs to be Elixir **root** path, i.e. the top level repo directory ([elixir-lang/elixir](https://github.com/elixir-lang/elixir)). 

Ah, and of course there is a "minor" issue with embedding Elixir. Escript file size grows. By 2.6M. That's more than 200%. 😢 

Anyway, I encourage you try it out. Basic check would be to run `erlangpl` with `-vvv` flag and see if there is proper message in the logs: `Couldn't start Elixir` when Elixir is not embedded nor path was provided, or `Successfully loaded and started Elixir`. It works on my machine, but I'd appreciate feedback, especially with `bootstrap`.

2017-04-01 22:53 UTC, arkgil commented
I've made some small changes:
* modules are treated as plugins when their names end with `EPL`, not `_EPL`
* path to plugin's ebin is added to code path before we attempt to load anything - when trying to create [Elixir example](https://github.com/erlanglab/epl_counter), erlangpl tried to load one of the modules before loading `.app` file, which completely broke loading flow and everything crashed. This shouldn't happen with introduced changes, but I wonder if there are any consequences.

There is one issue I noticed when writing an example: URL to websocket handler is `ws://localhost:8000/Elixir.EPLCounter.EPL`, because it's constructed based on plugin's module name. But it's only visual problem, so not that important now.

2017-04-02 14:20 UTC, arkgil commented
I'll appreciate code-wise feedback 🙂

2017-04-03 06:19 UTC, michalslaski requested changes

2017-04-03 06:19 UTC, michalslaski commented on apps/epl/src/epl_app.erl
> +     {elixir_path, $e, "with-elixir", string, "Path to Elixir root directory"}
Try to preserve formatting of this function, e.g. change elixir_path to just elixir and ensure indentation is the same as above.

2017-04-03 06:19 UTC, michalslaski commented on bootstrap
> +    Contents = file_contents(Path),
After this line call beam_lib:strip/1 to remove debug_info symbols and thus reduce size of the output escript.

2017-04-03 06:22 UTC, michalslaski commented on bootstrap
>      {ok, Bin} = file:read_file(Filename),
Maybe even call beam_lib:strip/1 here to ensure future plugins are always stripped.

2017-04-03 21:10 UTC, arkgil commented
Well, that was impressive. Script size reduced to 2.4M again 👍

2017-04-03 21:11 UTC, arkgil commented
I think there is nothing more to be done regarding initial integration with Elixir. Probably more issues will come up when we start to use it.

2017-04-04 07:11 UTC, michalslaski approved these changes

2017-04-04 07:13 UTC, michalslaski commented
I hope no Elixir program depends on debug_info symbols of the core libraries and I'm going to merge it.

2017-04-04 07:14 UTC, merged